### ISSUE TITLE
Neispravna poveznica na sliku u README.md ?

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Fuel-gauge-BQ27441-breakout-hardware-design#1]
https://github.com/SolderedElectronics/Fuel-gauge-BQ27441-breakout-hardware-design/blob/0091927603dd9f9bc993aa76f1bbfd97a8a1e5ea/README.md?plain=1#L5C34-L5C161

umjesto:

https://github.com/SolderedElectronics/Fuel-gauge-BQ27441-breakout-hardware-design/blob/main/OUTPUTS/V1.1.1/333065.jpg?raw=true

čini mi se da bi trebalo biti:

https://github.com/SolderedElectronics/Fuel-gauge-BQ27441-breakout-hardware-design/blob/main/OUTPUTS/V1.0.0/333065.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
